### ISSUE TITLE
Suggestion: Reflect on state to find valid events on this state.

### ISSUE THREAD

**Issue by bradphelan** [appccelerate/appccelerate#16]
I have defined a state machine with the following states and events

``` cs
public enum States
{
    Paused,
    Playing,
}

public enum Events
{
    Pause,
    Play,
    FastForward,
    Rewind
}
```

and the following FSM definition

``` cs
public MeshingAnimator()
{
    _fsm = new PassiveStateMachine<States, Events>();
    _fsm.Initialize(States.Paused);

    _fsm
        .In(States.Paused)
        .On(Events.Play)
        .Goto(States.Playing);

    _fsm
        .In(States.Paused)
        .On(Events.FastForward)
        .Execute(() => Jog(Math.PI / 10));

    _fsm
        .In(States.Paused)
        .On(Events.Rewind)
        .Execute(() => Jog(-Math.PI / 10));

    _fsm
        .In(States.Playing)
        .On(Events.Pause)
        .Goto(States.Paused);


    _fsm.In(States.Playing)
        .ExecuteOnEntry(() => Play());

    _fsm.In(States.Playing)
        .ExecuteOnExit(() => Stop());

}
```

via reflection I am generating XAML Command objects for each event using the 
below code.

```
Commands = new EnumerationToReactiveCommand<Events>(_fsm.Fire);
```

which generates a C# dynamic object with dynamic properties for each event
in the enumeration and which delegates the event to the FSM fire methore. 
In XAML I can bind to the command like so

```
<Button
    Style="{StaticResource tool}" 
    Command="{Binding Path=Animation.Commands.Rewind}">
    &lt;&lt; </Button>

<Button
    Style="{StaticResource tool}" 
    Command="{Binding Path=Animation.Commands.Play}">
    &gt;</Button>

<Button
    Style="{StaticResource tool}" 
    Command="{Binding Path=Animation.Commands.Pause}">
    | |</Button>

<Button
    Style="{StaticResource tool}" 
    Command="{Binding Path=Animation.Commands.FastForward}">
    &gt;&gt; </Button>
```

Now this all works fine but I'd like to be able to do another thing. I would
like to be able to reflect on the statemachine and know for a given state which
events are available. Then for the generated command object I can set it to
be enabled or disabled if the associated event is available or not. 

However I cannot find a way to reflect on the FSM or it's states to find 
events for a specific state.

**Comment by ursenzler** [comment]
Hi Brad

Accessing the "enabled" event of the current state of a state machine is a tricky thing. The problem is the current state. Of course there is an internal current state, but it is not guaranteed that this state is the also the state that is observed to be the current state from the outside. (yes it's complicated :-) )

If there are queued events on the state machine, the external current state could be different from the internal current state. Now, this is a big problem for ActiveStateMachines and not for the PassiveStateMachine. However, I don't want to implement different internals for these two machines.

That's why I cannot give you a general solution. But there is a solution for your specific problem (actually there are two):

1)
You can write an extension (derive from ExtensionBase (in namespace Extensions) or implement IExtension) and add it to the state machine (AddExtension).
In your extension you can implement the method SwitchedState so that it looks at the transitions of the new state (newState.Transitions.GetTransitions().Select(t => t.EventId) ). This gives you all "enabled" transitions. You then have to store the currently "enabled" events somewhere so that your view-model can check them.

2)
You implement EntryActions for each state that keep track of which events are "enabled". This way you make the internally possible events externally visible, without risking inconsistencies (see above).

Solution 1 is more generic, solution 2 is simpler.

I hope this helps you. Feel free to ask follow-up questions.

Happy coding
Urs

**Comment by bradphelan** [comment]
Thanks for that info, I'll give that a try

**Comment by ursenzler** [comment]
Did it work?

**Comment by bradphelan** [comment]
Sorry I haven't tried it yet. I've been distracted with other issues. I'll
eventually get around back to this.

Thanks for following up.

Regards

Brad
