### ISSUE TITLE
State Machine Usage

### ISSUE THREAD

**Issue by clauchiorean** [appccelerate/appccelerate#25]
Hi. 

Do You always create a one class state machine in your projects that controls everything (hierarchical ones)?
Do you create multiple smaller state machines and use some Mediator to communicate between them?
Do you always use state Enums for you states?
How do you fire events in the state machine?

Do you create some abstraction over the state machine or just use it inside a class?

**Comment by ursenzler** [comment]
_Do You always create a one class state machine in your projects that controls everything (hierarchical ones)?_
Depends on what you understand by everything. We use a dedicated state machine 
- per instrument we abstract, 
- per UI flow (e.g. disabling of elements on a single view)

_Do you create multiple smaller state machines and use some Mediator to communicate between them?_
see above

_Do you always use state Enums for you states?_
Mostly, but you can use strings or classes implementing IComparable, too.

_How do you fire events in the state machine?_
You can fire an event in a transition, entry or exit action. The event will be queued by the state machine (see http://www.appccelerate.com/statemachinepassivestatemachine.html)

_Do you create some abstraction over the state machine or just use it inside a class?_
If the state machine abstract some device or component, we wrap it with a class providing methods that will call then the state machine with Events. So the events are internal to this wrapper class. This way, you don't get to closely coupled to the state machine. Often, this wrapper class also keeps track of some externally visible state so you don't need to rely on the internal state of the state machine.

**Comment by clauchiorean** [comment]
Thanks for the answers.

_Do you always use state Enums for you states?
Mostly, but you can use strings or classes implementing IComparable, too._

When you use classes implemeting IComparable do you impelemnt entry and exit actions as methods the state classes or every action is implemented int the class that wraps the state machine?
I guess transition actions need to be implemented int the class that wraps the state machine. Am I write(I guess is much easier)?

_How do you fire events in the state machine?
You can fire an event in a transition, entry or exit action. The event will be queued by the state machine (see http://www.appccelerate.com/statemachinepassivestatemachine.html)_

I was mostly interested if you use some EventBoker to send messages (with some payload maybe) to the state machine containing the event to fire?

_Do you create some abstraction over the state machine or just use it inside a class?
If the state machine abstract some device or component, we wrap it with a class providing methods that will call then the state machine with Events. So the events are internal to this wrapper class. This way, you don't get to closely coupled to the state machine. Often, this wrapper class also keeps track of some externally visible state so you don't need to rely on the internal state of the state machine._

What to do you mean by externally visible state? Can you provide an example?

Ho do you unit test a component that uses a state machine?

**Comment by ursenzler** [comment]
_When you use classes implemeting IComparable do you impelemnt entry and exit actions as methods the state classes or every action is implemented int the class that wraps the state machine?_

I seldom use classes for state - mostly enums, some strings. All actions - entry, exit, transition -actions, should be placed in the class holding the state machine so you can call them using the fluent definition syntax.

_I was mostly interested if you use some EventBoker to send messages (with some payload maybe) to the state machine containing the event to fire?_

Normally, I fire an event to the state machine from a public method (or an event handler method) of the class holding the state machine. The actual state machine is therefore an implementation detail and not visible externally of the class holding it. This also simplifies unit testing. 

_What to do you mean by externally visible state? Can you provide an example?_
Because the state machine is an implementation detail, the states of the Appccelerate state machine are "internal". And we made the experience that it is better, not to make them visible directly to the rest of the system. Externally, you should rely on "external states" by using flags or effects made by actions (e.g. setting a visible flag on a UI control). If you separate internal and external states, you can refactor the state machine (e.g. splitting a single state into two states to make the state machine simpler) without effects on the rest of your system. 
You may have noticed that you cannot access the current state of the state machine directly. The current state is a tricky thing (especially in an active state machine, working asynchronously on its own worker thread), because there may be events already queued that will change the current state immediately. Therefore, it is risky to act (fire events onto the state machine) directly based on the current state. If you introduce "external" states (e.g. WeAreInitializedNow or ElevatorMovement = { Down, Up, None }) hold in the class holding the state machine, you get more control what and when these states are accessed.

_How do you unit test a component that uses a state machine?_
Because the Appccelerate state machine is just an implementation detail of the class holding it, I can simply unit test the class holding the state machine by calling the public methods, which will fire events onto the state machine, and checking whether the correct methods on other objects were called by the actions.

You find a sample how we use the state machine, together with some tests here: https://github.com/appccelerate/sensorsample
